server:
  port: 8081


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aaron
    username: spring
    password: boot
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

